/* Generated By:JJTree: Do not edit this line. /Users/richard/WIQA Framework/workspace/NG4J/src/de/fuberlin/wiwiss/ng4j/triql/parser/TriQLParserTreeConstants.java */

package de.fuberlin.wiwiss.ng4j.triql.parser;

public interface TriQLParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTQUERY = 1;
  public int JJTSELECTCLAUSE = 2;
  public int JJTSOURCECLAUSE = 3;
  public int JJTSOURCESELECTOR = 4;
  public int JJTGRAPHPATTERNCLAUSE = 5;
  public int JJTCONSTRAINTCLAUSE = 6;
  public int JJTGRAPHPATTERN = 7;
  public int JJTTRIPLEPATTERN = 8;
  public int JJTVAR = 9;
  public int JJTPREFIXESCLAUSE = 10;
  public int JJTPREFIXDECL = 11;
  public int JJTCOUNTEXPRESSION = 12;
  public int JJTLOGICALOR = 13;
  public int JJTLOGICALAND = 14;
  public int JJTSTRINGEQUAL = 15;
  public int JJTSTRINGNOTEQUAL = 16;
  public int JJTSTRINGMATCH = 17;
  public int JJTSTRINGNOMATCH = 18;
  public int JJTBITOR = 19;
  public int JJTBITXOR = 20;
  public int JJTBITAND = 21;
  public int JJTEQUAL = 22;
  public int JJTNOTEQUAL = 23;
  public int JJTLESSTHAN = 24;
  public int JJTGREATERTHAN = 25;
  public int JJTLESSTHANOREQUAL = 26;
  public int JJTGREATERTHANOREQUAL = 27;
  public int JJTLEFTSHIFT = 28;
  public int JJTRIGHTSIGNEDSHIFT = 29;
  public int JJTRIGHTUNSIGNEDSHIFT = 30;
  public int JJTADD = 31;
  public int JJTSUBTRACT = 32;
  public int JJTMULTIPLY = 33;
  public int JJTDIVIDE = 34;
  public int JJTMODULUS = 35;
  public int JJTUNARYPLUS = 36;
  public int JJTUNARYMINUS = 37;
  public int JJTUNARYNOT = 38;
  public int JJTNUMERICLITERAL = 39;
  public int JJTTEXTLITERAL = 40;
  public int JJTPATTERNLITERAL = 41;
  public int JJTBOOLEANLITERAL = 42;
  public int JJTNULLLITERAL = 43;
  public int JJTURL = 44;
  public int JJTQNAME = 45;
  public int JJTQUOTEDURI = 46;
  public int JJTIDENTIFIER = 47;


  public String[] jjtNodeName = {
    "void",
    "Query",
    "SelectClause",
    "SourceClause",
    "SourceSelector",
    "GraphPatternClause",
    "ConstraintClause",
    "GraphPattern",
    "TriplePattern",
    "Var",
    "PrefixesClause",
    "PrefixDecl",
    "CountExpression",
    "LogicalOr",
    "LogicalAnd",
    "StringEqual",
    "StringNotEqual",
    "StringMatch",
    "StringNoMatch",
    "BitOr",
    "BitXor",
    "BitAnd",
    "Equal",
    "NotEqual",
    "LessThan",
    "GreaterThan",
    "LessThanOrEqual",
    "GreaterThanOrEqual",
    "LeftShift",
    "RightSignedShift",
    "RightUnsignedShift",
    "Add",
    "Subtract",
    "Multiply",
    "Divide",
    "Modulus",
    "UnaryPlus",
    "UnaryMinus",
    "UnaryNot",
    "NumericLiteral",
    "TextLiteral",
    "PatternLiteral",
    "BooleanLiteral",
    "NullLiteral",
    "URL",
    "QName",
    "QuotedURI",
    "Identifier",
  };
}
