/* CVS $Id: SWP.java,v 1.1 2004/11/27 20:19:08 erw Exp $ */

package de.fuberlin.wiwiss.ng4j.swp.vocabulary;
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from swp.owl 
 * @author Auto-generated by schemagen on 05 Oct 2004 21:13 
 */
public class SWP {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2004/03/trix/swp-1/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The subject graph originates from and is asserted by the authority specified 
     *  for the object warrant. The statements expressed in the graph are taken to 
     *  be claims made by that authority. This property has performative semantics.</p>
     */
    public static final Property assertedBy = m_model.createProperty( "http://www.w3.org/2004/03/trix/swp-1/assertedBy" );
    
    /** <p>The object is the signature to be used to authenticate the graph with which 
     *  the subject warrant is associated.</p>
     */
    public static final Property signature = m_model.createProperty( "http://www.w3.org/2004/03/trix/swp-1/signature" );
    
    /** <p>The object is the certification authority issuing the certificate specified 
     *  for the warrant.</p>
     */
    public static final Property certificationAuthority = m_model.createProperty( "http://www.w3.org/2004/03/trix/swp-1/certificationAuthority" );
    
    /** <p>The object is a certificate by which the authority specified for the warrant 
     *  can be authenticated.</p>
     */
    public static final Property certificate = m_model.createProperty( "http://www.w3.org/2004/03/trix/swp-1/certificate" );
    
    /** <p>The object is a certificate by which the authority specified for the warrant 
     *  can be authenticated.</p>
     */
    public static final Property caCertificate = m_model.createProperty( "http://www.w3.org/2004/03/trix/swp-1/caCertificate" );
    
    /** <p>The subject graph originates from the authority specified for the object warrant. 
     *  The statements expressed in the graph are not taken to be claims made by that 
     *  authority, insofar as any statement using this property is concerned.</p>
     */
    public static final Property quotedBy = m_model.createProperty( "http://www.w3.org/2004/03/trix/swp-1/quotedBy" );
    
    /** <p>The object is the signature method by which the signature specified for the 
     *  warrant subject was constructed.</p>
     */
    public static final Property signatureMethod = m_model.createProperty( "http://www.w3.org/2004/03/trix/swp-1/signatureMethod" );
    
    /** <p>The object authority is the origin of the graph with which the subject warrant 
     *  is associated.</p>
     */
    public static final Property authority = m_model.createProperty( "http://www.w3.org/2004/03/trix/swp-1/authority" );
    
    /** <p>A relationship between an authority and a graph, in which the authority is 
     *  in some way an origin of that graph. Warrants may include a digital signature 
     *  of the graph by the authority.</p>
     */
    public static final Resource Warrant = m_model.createResource( "http://www.w3.org/2004/03/trix/swp-1/Warrant" );
    
    /** <p>An authority which issues certificates.</p> */
    public static final Resource CertificationAuthority = m_model.createResource( "http://www.w3.org/2004/03/trix/swp-1/CertificationAuthority" );
    
    /** <p>A method used to construct a signature used to authenticate a graph.</p> */
    public static final Resource SignatureMethod = m_model.createResource( "http://www.w3.org/2004/03/trix/swp-1/SignatureMethod" );
    
    /** <p>An authority, or origin, of a graph; such as a person or company.</p> */
    public static final Resource Authority = m_model.createResource( "http://www.w3.org/2004/03/trix/swp-1/Authority" );
    
    public static final Resource SignatureMethodConstant = m_model.createResource( "http://grid.cx/2004/11/24/rdf-sig-method" );
    
    public static final Resource C14NAlgorithm = m_model.createResource( "http://grid.cx/2004/11/24/rdf-c14n-alg" );
    
    public static final Resource HashAlgorithm = m_model.createResource( "http://grid.cx/2004/11/24/rdf-rsa-sha1-alg" );
    
}

/*
 *  (c)   Copyright 2004 Rowland Watkins (rowland@grid.cx) & University of 
 * 		  Southampton, Declarative Systems and Software Engineering Research 
 *        Group, University of Southampton, Highfield, SO17 1BJ
 *   	  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
