package de.fuberlin.wiwiss.trust;

import java.util.Iterator;

import com.hp.hpl.jena.graph.Triple;

/**
 * <p>A service that encapsulates the generation of an {@link Explanation}
 * for a given triple and trust policy. This process has three main parts:</p>
 * 
 * <ol>
 * <li>Find the bindings with ?SUBJ, ?PRED and ?OBJ matching the triple</li>
 * <li>Instantiate the current trust policy's explanation template using
 *   these bindings</li>
 * <li>Add any explanations generated by metrics; they are stored in the
 *   bindings.</li>
 * </ol>
 * 
 * @version $Id: Explainer.java,v 1.4 2005/10/04 00:03:44 cyganiak Exp $
 * @author Richard Cyganiak (richard@cyganiak.de)
 */
public class Explainer {
    private ResultTable results;
    private Triple triple;
    private TrustPolicy policy;
    
    /**
     * Creates a new explainer.
     * @param results The results from a query against the trust engine
     * @param tripleToExplain A triple from the results that should be explained
     * @param policyInUse The trust policy that was used in the query
     */
    public Explainer(ResultTable results, Triple tripleToExplain, TrustPolicy policyInUse) {
        this.policy = policyInUse;
        this.triple = tripleToExplain;
        this.results = results.selectMatching(tripleToExplain);
        if (this.results.countBindings() == 0) {
            throw new IllegalArgumentException("Triple " + tripleToExplain
                    + " is not in result tabe");
        }
    }
    
    /**
     * @return An explanation why the triple matched the policy.
     */
    public Explanation explain() {
        Explanation result = new Explanation(this.triple, this.policy);
        if (this.policy.getExplanationTemplate() == null) {
            return result;
        }
        Iterator it = this.policy.getExplanationTemplate().instantiateTree(this.results).iterator();
        while (it.hasNext()) {
            ExplanationPart part = (ExplanationPart) it.next();
            result.addPart(part);
        }
        // append constraint explanation parts
        Iterator bindings = this.results.bindingIterator();
        while(bindings.hasNext()){
            VariableBinding binding = (VariableBinding) bindings.next();
            
            // add text explanations
            Iterator textExpls = binding.getTextExplanations().iterator();
            while(textExpls.hasNext()){
                result.addPart((ExplanationPart) textExpls.next());
            }
            
            //TODO: add graphs with RDF explanations to explanations
        }
        
        return result;
    }
}
