package de.fuberlin.wiwiss.trust;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.hp.hpl.jena.graph.Graph;
import com.hp.hpl.jena.graph.Node;

/**
 * @version $Id: VariableBinding.java,v 1.4 2005/05/24 13:50:27 maresch Exp $
 * @author Richard Cyganiak (richard@cyganiak.de)
 * @author Oliver Maresch (oliver-maresch@gmy.de)
 */
public class VariableBinding {
    private Map namesToValues;
    
    /** Contains a list of  ExplanationPart generated by the contstraint checking.*/
    private List textExplanations;

    /** Contains a list of  Graphs with RDF explanations generated by the contstraint checking.*/
    private List graphExplanations;

    public VariableBinding() {
        this(new HashMap());
    }
    
    public VariableBinding(Map binding) {
        this.namesToValues = binding;
        textExplanations = new ArrayList();
        graphExplanations = new ArrayList();
    }
    
    /**
     * Adds a ExplanationPart to the list of text explanations
     */
    public void addTextExplanation(ExplanationPart textExplanation){
        this.textExplanations.add(textExplanation);
    }
    
    /** 
     * Returns the list of text explanations. The list contains ExplanationParts.
     */
    public List getTextExplanations(){
        return this.textExplanations;
    }
    
    /**
     * Adds a Graph with a RDF Explanation to the list of graph explanations
     */
    public void addGraphExplanation(Graph graphExplanation){
        this.graphExplanations.add(graphExplanation);
    }
    
    /** 
     * Returns the list of graph explanations. The list contains Graphs.
     */
    public List getGraphExplanations(){
        return this.graphExplanations;
    }
    
    public boolean containsName(String variableName) {
        return this.namesToValues.containsKey(variableName);
    }
    
    public Node value(String variableName) {
        return (Node) this.namesToValues.get(variableName);
    }
    
    public void setValue(String variableName, Node variableValue) {
        this.namesToValues.put(variableName, variableValue);
    }
    
    public Set variableNames() {
        return this.namesToValues.keySet();
    }
    
    public Map asMap() {
        return Collections.unmodifiableMap(this.namesToValues);
    }
    
    public VariableBinding selectSubset(Collection variableNames) {
        VariableBinding result = new VariableBinding();
        Iterator it = variableNames.iterator();
        while (it.hasNext()) {
            String variableName = (String) it.next();
            if (!containsName(variableName)) {
                continue;
            }
            result.setValue(variableName, value(variableName));
        }
        return result;
    }
    
    public boolean isSubsetOf(VariableBinding other) {
        Iterator it = this.namesToValues.keySet().iterator();
        while (it.hasNext()) {
            String variableName = (String) it.next();
            Node value = value(variableName);
            if (value == null && other.value(variableName) != null) {
                return false;
            }
            if (value != null && !value.equals(other.value(variableName))) {
                return false;
            }
        }
        return true;
    }
    
    public String toString() {
        return "VariableBinding" + this.namesToValues;
    }
    
    public boolean equals(Object other) {
        VariableBinding otherBinding = (VariableBinding) other;
        return otherBinding.namesToValues.equals(this.namesToValues);
    }
    
    public int hashCode() {
        return this.namesToValues.hashCode();
    }
}
